name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Show versions
        run: |
          go version
          make --version || true

      - name: Build Go (repo root)
        run: go build -v ./...

      - name: Build .deb if Makefile exists
        run: |
          if [ -f Makefile ]; then
            make deb || true
          fi

      - name: Upload .deb artifact (if any)
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages
          path: "*.deb"
          if-no-files-found: ignore
