name: Release (Go only)
on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: write
  packages: write

jobs:
  go_container_and_deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build & push Docker image to GHCR
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/gosvc:${GITHUB_REF_NAME#v}
          docker buildx build --platform linux/amd64 -t $IMAGE --push .

      # Build .deb using Makefile at repo root
      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }
      - name: Build .deb
        run: make deb VERSION=${GITHUB_REF_NAME#v} || true

      # Create GitHub Release and attach .deb
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            *.deb
