name: Release (Go only)

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository }}/gosvc

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Compute TAG (strip 'v')
        run: |
          echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "TAG=$TAG"

      # Optional: run tests before releasing
      - name: Test
        run: go test ./...

      # ---- Build & Push multi-arch image ----
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image (amd64 + arm64)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "$IMAGE:$TAG" \
            -t "$IMAGE:latest" \
            --push \
            .

      # ---- Build .deb (nếu Makefile có target deb) ----
      - name: Build .deb package
        run: |
          make deb VERSION="$TAG" || true

      # ---- Tạo Release & đính kèm file ----
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            *.deb
            dist/*.deb
